# Configuration for both local development and Pages
name = "buzzline"
compatibility_date = "2024-10-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./"

# KV Namespaces
[[kv_namespaces]]
binding = "BUZZLINE_MAIN"
id = "365db24eb7d647acb6e3fc39d38acd25"
preview_id = "fa6543997a044e459690a1798bff62be"

[[kv_namespaces]]
binding = "BUZZLINE_ANALYTICS"
id = "45f26618ca3042ee8c90df3ac3b5ff2b"
preview_id = "0c5d091149a74d4bbac8941b678a6caa"

[[kv_namespaces]]
binding = "BUZZLINE_CACHE"
id = "951b33a733c446378409d0825256c060"
preview_id = "9082b80ad91d4e5f9b2da6a086871817"